name: CI - Build Docker image

# Grant minimal permissions required to push to GHCR. If your organization
# disallows creation of organization packages via the GITHUB_TOKEN, create a
# personal access token (PAT) with `write:packages` (and `repo` if needed) and
# add it to this repository's secrets as `GHCR_PAT`.
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Prefer a user PAT stored in GHCR_PAT (recommended for org repos).
          # Fall back to the automatically provided GITHUB_TOKEN when that
          # is permitted by the organization.
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/modernize-cobol-to-python:latest
